args:

  device: cuda
<<<<<<< HEAD:configs/SEU_010ablation/config_TSPN_onlymean_std.yaml
  data_dir: '/home/user/data/a_bearing/a_010_SEU_pro' # '/home/user/data/a_bearing/a_006_THU_pro/LQ_fusion/' '/home/user/data/a_bearing/a_018_THU24_pro/'
  dataset_task: SEU_Basic # THU_006_basic THU_006_generalization THU_006_fusion THU_018_basic THU_018_generalization THU_018_fusion
  target: 'SEU_bearing_20Hz_5' # if basic or generalization 1hz 10hz 15hz
=======
###################### data ##################

  # data_dir: 
  data_dir: 'C:/Users/CCSLab/Desktop/SEU_bearing/' # '/home/user/data/a_bearing/a_006_THU_pro/LQ_fusion/' '/home/user/data/a_bearing/a_018_THU24_pro/'
  dataset_task: SEU_010_Basic # THU_006_basic THU_006_generalization THU_006_fusion THU_018_basic THU_018_generalization THU_018_fusion
  target: 'SEU_bearing_20Hz_2' # if basic or generalization 1hz 10hz 15hz
>>>>>>> 0dc82ab752d9c8ef92e0403ced7c913e30c62be6:configs/SEU_010/config_TFN_basic.yaml
  k_shot: 64

# model
  model: 'TFN_Morlet' # 'Resnet' 'WKN_m' 'Sinc_net_m' 'Huan_net' 'TFN_Morlet' 'MCN_GFK'
  skip_connection: true
  num_classes: 5 # 5 for THU_018_basic 4 for THU_006_basic
  in_dim : 4096
  out_dim : 4096
  in_channels : 2
  out_channels : 3
  scale : 4

  f_c_mu: 0
  f_c_sigma: 0.1
  f_b_mu: 0
  f_b_sigma: 0.1


# hyperparameter
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 20
  weight_decay: 0.0001
  num_workers: 8
  seed: 17

# train
  monitor: 'val_loss'
  patience: 200
  gpus: 1
  weight_decay: 0.0001
  l1_norm: 0.0001

  pruning: None # [0.7,0.5,0.01]
  snr: 0
