signal_processing_configs:
  layer1: ['HT','MWF','I']
  layer2: ['HT','MWF','I']
  layer3: ['HT','MWF','I']
  layer4: ['HT','MWF','I'] 

feature_extractor_configs: ['Mean', 'Std', 'Var', 'Entropy','Max', 'Min', 'AbsMean', 'Kurtosis', 'RMS', 'CrestFactor','Skewness', 'ClearanceFactor', 'ShapeFactor']

args:

  device: cuda
  data_dir: '/home/user/data/a_bearing/a_006_THU_pro/LQ_fusion/' # '/home/user/data/a_bearing/a_006_THU_pro/LQ_fusion/' '/home/user/data/a_bearing/a_018_THU24_pro/'
  dataset_task: THU_006_basic # THU_006_basic THU_006_generalization THU_006_fusion THU_018_basic THU_018_generalization THU_018_fusion
  target: '10hz' # if basic or generalization 1hz 10hz 15hz
  k_shot: 64


# model
  model: TSPN
  skip_connection: True
  num_classes: 4
  in_dim : 4096
  out_dim : 4096
  in_channels : 2
  out_channels : 3
  scale : 4

  f_c_mu: 0
  f_c_sigma: 0.1
  f_b_mu: 0
  f_b_sigma: 0.1

# hyperparameter
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 300
  weight_decay: 0.0001
  num_workers: 32
  seed: 17

# train
  monitor: 'val_loss'
  patience: 16
  gpus: 1
  weight_decay: 0.0001
  l1_norm: 0.001

  log_parameters: True

  pruning: None # [0.7,0.5,0.01]
  snr: False

  ##   parameter

  # Ricker
  Ricker_sigma: 0.01

  # Chirplet
  Chirplet_sigma: 1
  Chirplet_omega: 0.5
  Chirplet_alpha: 500

  # Laplace

  Laplace_A: 1
  Laplace_ep: 0.03
  Laplace_tal: 0.1
  Laplace_f: 10

  # Morlet

  Morlet_f_b: 10
  Morlet_f_c: 10

  # sigma: 0.52
  # omega: 0.1
  # alpha: 0.1
