signal_processing_configs:
  layer1: ['HT','LNO','I']
  layer2: ['HT','LNO','I']
  layer3: ['HT','LNO','I']
  layer4: ['HT','LNO','I']

feature_extractor_configs: ['Mean', 'Std']

args:

  device: cuda
  data_dir: 'C:/Users/CCSLab/Desktop/HUST_bearing/' 
  dataset_task: HUST_031_Basic
  target: 'HUST_bearing_VS_0_40_0Hz' # HUST_bearing_20Hz, HUST_bearing_VS_0_40_0Hz
  k_shot: 64


# model
  model: TSPN
  skip_connection: true
  num_classes: 9
  in_dim : 4096
  out_dim : 4096
  in_channels : 3
  out_channels : 3
  scale : 4

  f_c_mu: 0
  f_c_sigma: 0.1
  f_b_mu: 0
  f_b_sigma: 0.1

# hyperparameter
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 30
  weight_decay: 0.0001
  num_workers: 8
  seed: 17

# train
  monitor: 'val_loss'
  patience: 200
  gpus: 1
  weight_decay: 0.0001
  l1_norm: 0.0001

  pruning: None # [0.7,0.5,0.01]
  snr: 0