signal_processing_configs:
  layer1: ['I','I','I']
  layer2: ['I','I','I']
  layer3: ['I','I','I']
  layer4: ['I','I','I']

feature_extractor_configs: ['Mean', 'Std', 'Var', 'Entropy','Max', 'Min', 'AbsMean', 'Kurtosis', 'RMS', 'CrestFactor','Skewness', 'ClearanceFactor', 'ShapeFactor']

args:

  device: cuda
  data_dir: '/home/user/data/a_bearing/a_031_HUST_pro' 
  dataset_task: SEU_010_Basic 
  target: 'SEU_bearing_20Hz_2' # SEU_bearing_20Hz_2, SEU_bearing_30Hz_2
  k_shot: 64


# model
  model: TSPN
  skip_connection: true
  num_classes: 5
  in_dim : 4096
  out_dim : 4096
  in_channels : 2
  out_channels : 3
  scale : 4

  f_c_mu: 0
  f_c_sigma: 0.1
  f_b_mu: 0
  f_b_sigma: 0.1

# hyperparameter
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 20
  weight_decay: 0.0001
  num_workers: 8
  seed: 17

# train
  monitor: 'val_loss'
  patience: 200
  gpus: 1
  weight_decay: 0.0001
  l1_norm: 0.0001

  pruning: None # [0.7,0.5,0.01]
  snr: 0