signal_processing_configs:
  layer1: ['HT','LNO','I']
  layer2: ['HT','LNO','I']
  layer3: ['HT','LNO','I']
  layer4: ['HT','LNO','I']

feature_extractor_configs: ['Mean', 'Std', 'Var', 'Entropy','Max', 'Min', 'AbsMean', 'Kurtosis', 'RMS', 'CrestFactor','Skewness', 'ClearanceFactor', 'ShapeFactor']

args:

  device: cuda
  data_dir: '/home/user/data/a_bearing/a_031_HUST_pro/'
  dataset_task: a_031_HUST_generalization
  source: ['HUST_bearing_20Hz','HUST_bearing_80Hz','HUST_bearing_40Hz','HUST_bearing_60Hz']
  target: ['HUST_bearing_VS_0_40_0Hz'] # HUST_bearing_20Hz, HUST_bearing_VS_0_40_0Hz
  k_shot: 64'
  fs: 25600


# model
  model: TSPN
  skip_connection: false
  num_classes: 9
  in_dim : 4096
  out_dim : 4096
  in_channels : 3
  out_channels : 3
  scale : 4

  f_c_mu: 0
  f_c_sigma: 0.1
  f_b_mu: 0
  f_b_sigma: 0.1

# hyperparameter
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 200
  weight_decay: 0.0001
  num_workers: 32
  seed: 17

# train
  monitor: 'val_loss'
  patience: 100
  gpus: 1
  weight_decay: 0.0001
  l1_norm: 0.0001

  pruning: None # [0.7,0.5,0.01]
  snr: 0