signal_processing_configs:
  layer1: ['HT','WF','I']
  layer2: ['HT','WF','I']
  layer3: ['HT','WF','I']
  layer4: ['HT','WF','I']

feature_extractor_configs: ['Mean', 'Std', 'Var', 'Entropy','Max', 'Min', 'AbsMean', 'Kurtosis', 'RMS', 'CrestFactor','Skewness', 'ClearanceFactor', 'ShapeFactor']

args:

  device: cuda
  data_dir: 'C:/Users/CCSLab/Desktop/SUDA_electric/' 
  dataset_task: a_temp_SUDA_generalization
  source: ['SUDA_electric_0kg_2500r_1000Hz', 'SUDA_electric_0kg_4000r_1000Hz', 'SUDA_electric_6kg_2500r_1000Hz', 'SUDA_electric_6kg_4000r_1000Hz']
  target: ['SUDA_electric_3kg_3500r_1000Hz']
  target_list: [['SUDA_electric_0kg_3000r_1000Hz'], ['SUDA_electric_0kg_3500r_1000Hz'], ['SUDA_electric_3kg_2500r_1000Hz'], ['SUDA_electric_3kg_3000r_1000Hz'], ['SUDA_electric_3kg_3500r_1000Hz'], ['SUDA_electric_3kg_4000r_1000Hz'], ['SUDA_electric_6kg_3000r_1000Hz'], ['SUDA_electric_6kg_3500r_1000Hz']]
  k_shot: 64


# model
  model: TSPN
  skip_connection: true
  num_classes: 4
  in_dim : 1024
  out_dim : 1024
  in_channels : 5
  out_channels : 3
  scale : 5

  f_c_mu: 0
  f_c_sigma: 0.1
  f_b_mu: 0
  f_b_sigma: 0.1

# hyperparameter
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 200
  weight_decay: 0.0001
  num_workers: 8
  seed: 17
  persistent_workers: True

# train
  monitor: 'val_loss'
  patience: 100
  gpus: 1
  weight_decay: 0.0001
  l1_norm: 0.0001

  pruning: None # [0.7,0.5,0.01]
  snr: 0